import {CountryItem} from "../types/Types";

export const countryCodes: CountryItem[] = [
    {
        "name": {
            "en": "Afghanistan",
            "ru": "Афганистан",
            "pl": "Afganistan",
            "ua": "Афганістан",
            "cz": "Afghánistán",
            "by": "Афганістан",
            "pt": "Afeganistão",
            "es": "Afganistán",
            "ro": "Afganistan",
            "bg": "Афганистан",
            "de": "Afghanistan",
            "fr": "L'Afghanistan",
            "nl": "Afghanistan",
            "it": "Afghanistan",
            "cn": "阿富汗",
            "zh": "阿富汗",
            "ee": "Afganistan",
            "jp": "アフガニスタン",
            "he": "אפגניסטן",
            "el": "Αφγανιστάν"
        },
        "dial_code": "+93",
        "code": "AF",
        "flag": "🇦🇫"
    },
    {
        "name": {
            "en": "Benin",
            "ru": "Бенин",
            "pl": "Benin",
            "ua": "Бенін",
            "cz": "Benin",
            "by": "Бенін",
            "pt": "Benim",
            "es": "Benín",
            "ro": "Benin",
            "bg": "Бенин",
            "de": "Benin",
            "fr": "Bénin",
            "nl": "Benin",
            "it": "Benin",
            "cn": "贝宁",
            "zh": "貝寧",
            "ee": "Benin",
            "jp": "ベナン",
            "he": "בנין",
            "el": "Μπενίν"
        },
        "dial_code": "+229",
        "code": "BJ",
        "flag": "🇧🇯"
    },
    {
        "name": {
            "en": "Botswana",
            "ru": "Ботсвана",
            "pl": "Botswana",
            "ua": "Ботсвана",
            "cz": "Botswana",
            "by": "Батсвана",
            "pt": "Botsuana",
            "es": "Botsuana",
            "ro": "Botswana",
            "bg": "Ботсвана",
            "de": "Botswana",
            "fr": "Botswana",
            "nl": "Botswana",
            "it": "Botswana",
            "cn": "博茨瓦纳",
            "zh": "博茨瓦納",
            "ee": "Botswana",
            "jp": "ボツワナ",
            "he": "בוצואנה",
            "el": "Μποτσουάνα"
        },
        "dial_code": "+267",
        "code": "BW",
        "flag": "🇧🇼"
    },
    {
        "name": {
            "en": "Cameroon",
            "ru": "Камерун",
            "pl": "Kamerun",
            "ua": "Камерун",
            "cz": "Kamerun",
            "by": "Камерун",
            "pt": "Camarões",
            "es": "Camerún",
            "ro": "Camerun",
            "bg": "Камерун",
            "de": "Kamerun",
            "fr": "Cameroun",
            "nl": "Kameroen",
            "it": "Camerun",
            "cn": "喀麦隆",
            "zh": "喀麥隆",
            "ee": "Kamerun",
            "jp": "カメルーン",
            "he": "קמרון",
            "el": "Καμερούν"
        },
        "dial_code": "+237",
        "code": "CM",
        "flag": "🇨🇲"
    },
    {
        "name": {
            "en": "Congo",
            "ru": "Конго",
            "pl": "Kongo",
            "ua": "Конго",
            "cz": "Kongo",
            "by": "Конга",
            "pt": "Congo-Brazzaville",
            "es": "Congo",
            "ro": "Congo",
            "bg": "Конго",
            "de": "Kongo",
            "fr": "Congo",
            "nl": "Congo",
            "it": "Congo",
            "cn": "刚果",
            "zh": "剛果",
            "ee": "Kongo",
            "jp": "コンゴ",
            "he": "קונגו",
            "el": "Δημοκρατία του Κονγκό"
        },
        "dial_code": "+242",
        "code": "CG",
        "flag": "🇨🇬"
    },
    {
        "name": {
            "en": "Cote d'Ivoire",
            "ru": "Кот-д'Ивуар",
            "pl": "Wybrzeże Kości Słoniowej",
            "ua": "Кот-д'Івуар",
            "cz": "Pobřeží slonoviny",
            "by": "Кот-д'Івуар",
            "pt": "Costa do Marfim",
            "es": "Costa de Marfil",
            "ro": "Coasta de Fildeș",
            "bg": "Кот д'Ивоар",
            "de": "Elfenbeinküste",
            "fr": "Côte d'Ivoire",
            "nl": "Ivoorkust",
            "it": "Costa d'Avorio",
            "cn": "科特迪瓦",
            "zh": "科特迪瓦",
            "ee": "Elevandiluurannik",
            "jp": "コートジボワール",
            "he": "חוף השנהב",
            "el": "Ακτή Ελεφαντοστού"
        },
        "dial_code": "+225",
        "code": "CI",
        "flag": "🇨🇮"
    },
    {
        "name": {
            "en": "Cyprus",
            "ru": "Кипр",
            "pl": "Cypr",
            "ua": "Кіпр",
            "cz": "Kypr",
            "by": "Кіпр",
            "pt": "Chipre",
            "es": "Chipre",
            "ro": "Cipru",
            "bg": "Кипър",
            "de": "Zypern",
            "fr": "Chypre",
            "nl": "Cyprus",
            "it": "Cipro",
            "cn": "塞浦路斯",
            "zh": "塞浦路斯",
            "ee": "Küpros",
            "jp": "キプロス",
            "he": "קפריסין",
            "el": "Κύπρος"
        },
        "dial_code": "+357",
        "code": "CY",
        "flag": "🇨🇾"
    },
 {
        "name": {
            "en": "Eswatini",
            "ru": "ВСвате",
            "pl": "wSwacie",
            "ua": "УСваті",
            "cz": "VeSwatu",
            "by": "УСват",
            "pt": "EmSwat",
            "es": "Eswatini",
            "ro": "Eswatini",
            "bg": "ВСуат",
            "de": "Eswatini",
            "fr": "Eswatini",
            "nl": "Eswatini",
            "it": "Eswatini",
            "cn": "在斯瓦特",
            "zh": "在斯瓦特",
            "ee": "InSwat",
            "jp": "スワットで",
            "he": "בסוואט",
            "el": "ΣτοΣουάτ"
        },
        "dial_code": "+268",
        "code": "SZ",
        "flag": "🇸🇿"
    },
    {
        "name": {
            "en": "Ghana",
            "ru": "Гана",
            "pl": "Ghana",
            "ua": "Гана",
            "cz": "Ghana",
            "by": "Гана",
            "pt": "Gana",
            "es": "Ghana",
            "ro": "Ghana",
            "bg": "Гана",
            "de": "Ghana",
            "fr": "Ghana",
            "nl": "Ghana",
            "it": "Ghana",
            "cn": "加纳",
            "zh": "加納",
            "ee": "Ghana",
            "jp": "ガーナ",
            "he": "גאנה",
            "el": "Γκάνα"
        },
        "dial_code": "+233",
        "code": "GH",
        "flag": "🇬🇭"
    },
    {
        "name": {
            "en": "Guinea",
            "ru": "Гвинея",
            "pl": "Gwinea",
            "ua": "Гвінея",
            "cz": "Guinea",
            "by": "Гвінея",
            "pt": "Guiné",
            "es": "Guinea",
            "ro": "Guineea",
            "bg": "Гвинея",
            "de": "Guinea",
            "fr": "Guinée",
            "nl": "Guinea",
            "it": "Guinea",
            "cn": "几内亚",
            "zh": "幾內亞",
            "ee": "Guinea",
            "jp": "ギニア",
            "he": "גינאה",
            "el": "Γουινέα"
        },
        "dial_code": "+224",
        "code": "GN",
        "flag": "🇬🇳"
    },
    {
        "name": {
            "en": "Guinea-Bissau",
            "ru": "Гвинея-Бисау",
            "pl": "Gwinea Bissau",
            "ua": "Гвінея-Бісау",
            "cz": "Guinea-Bissau",
            "by": "Гвінея-Бісаў",
            "pt": "Guiné-Bissau",
            "es": "Guinea-Bissau",
            "ro": "Guineea-Bissau",
            "bg": "Гвинея-Бисау",
            "de": "Guinea-Bissau",
            "fr": "Guinée-Bissau",
            "nl": "Guinee-Bissau",
            "it": "Guinea-Bissau",
            "cn": "几内亚比绍",
            "zh": "幾內亞比紹",
            "ee": "Guinea-Bissau",
            "jp": "ギニアビサウ",
            "he": "גינאה-ביסאו",
            "el": "Γουινέα-Μπισσάου"
        },
        "dial_code": "+245",
        "code": "GW",
        "flag": "🇬🇼"
    },
    {
        "name": {
            "en": "Iran, Islamic Republic of",
            "ru": "Иран, Исламская Республика",
            "pl": "Iran, Republika Islamska",
            "ua": "Іран, Ісламська Республіка",
            "cz": "Írán, Islámská Republika",
            "by": "Іран, Ісламская Рэспубліка",
            "pt": "Irão",
            "es": "Irán, República Islámica de",
            "ro": "Iran (Republica Islamica a",
            "bg": "Иран, Ислямска република",
            "de": "Iran, Islamische Republik",
            "fr": "Iran (République islamique d",
            "nl": "Iran, Islamitische Republiek",
            "it": "Iran (Repubblica Islamica del",
            "cn": "伊朗伊斯兰共和国",
            "zh": "伊朗伊斯蘭共和國",
            "ee": "Iraan, Iraagi Islamivabariik",
            "jp": "イラン、イスラム共和国",
			"he": "איראן",
            "el": "Ιράν"
        },
        "dial_code": "+98",
        "code": "IR",
        "flag": "🇮🇷"
    },
    {
        "name": {
            "en": "Liberia",
            "ru": "Либерия",
            "pl": "Liberia",
            "ua": "Ліберія",
            "cz": "Libérie",
            "by": "Ліберыя",
            "pt": "Libéria",
            "es": "Liberia",
            "ro": "Liberia",
            "bg": "Либерия",
            "de": "Liberia",
            "fr": "Libéria",
            "nl": "Liberia",
            "it": "Liberia",
            "cn": "利比里亚",
            "zh": "利比里亞",
            "ee": "Libeeria",
            "jp": "リベリア",
            "he": "ליבריה",
            "el": "Λιβερία"
        },
        "dial_code": "+231",
        "code": "LR",
        "flag": "🇱🇷"
    },
    {
        "name": {
            "en": "Nigeria",
            "ru": "Нигерия",
            "pl": "Nigeria",
            "ua": "Нігерія",
            "cz": "Nigérie",
            "by": "Нігерыя",
            "pt": "Nigéria",
            "es": "Nigeria",
            "ro": "Nigeria",
            "bg": "Нигерия",
            "de": "Nigeria",
            "fr": "Nigeria",
            "nl": "Nigeria",
            "it": "Nigeria",
            "cn": "奈及利亚",
            "zh": "奈及利亞",
            "ee": "Nigeeria",
            "jp": "ナイジェリア",
            "he": "ניגריה",
            "el": "Νιγηρία"
        },
        "dial_code": "+234",
        "code": "NG",
        "flag": "🇳🇬"
    },
    {
        "name": {
            "en": "Rwanda",
            "ru": "Руанда",
            "pl": "Rwanda",
            "ua": "Руанда",
            "cz": "Rwanda",
            "by": "Руанда",
            "pt": "Ruanda",
            "es": "Ruanda",
            "ro": "Rwanda",
            "bg": "Руанда",
            "de": "Ruanda",
            "fr": "Rwanda",
            "nl": "Rwanda",
            "it": "Ruanda",
            "cn": "卢旺达",
            "zh": "盧旺達",
            "ee": "Rwanda",
            "jp": "ルワンダ",
            "he": "רואנדה",
            "el": "Ρουάντα"
        },
        "dial_code": "+250",
        "code": "RW",
        "flag": "🇷🇼"
    },
    {
        "name": {
            "en": "South Africa",
            "ru": "Южная Африка",
            "pl": "Afryka Południowa",
            "ua": "Південна Африка",
            "cz": "Jižní Afrika",
            "by": "Паўднёвая Афрыка",
            "pt": "África do Sul",
            "es": "Sudáfrica",
            "ro": "Africa de Sud",
            "bg": "Южна Африка",
            "de": "Südafrika",
            "fr": "Afrique du Sud",
            "nl": "Zuid-Afrika",
            "it": "Sud Africa",
            "cn": "南非",
            "zh": "南非",
            "ee": "Lõuna-Aafrika",
            "jp": "南アフリカ",
            "he": "דרום אפריקה",
            "el": "Νότια Αφρική"
        },
        "dial_code": "+27",
        "code": "ZA",
        "flag": "🇿🇦"
    },
    {
        "name": {
            "en": "South Sudan",
            "ru": "южный Судан",
            "pl": "Południowy Sudan",
            "ua": "Південний Судан",
            "cz": "jižní Súdán",
            "by": "Паўднёвы Судан",
            "pt": "Sudão do Sul",
            "es": "Sudán del Sur",
            "ro": "Sudul Sudanului",
            "bg": "Южен Судан",
            "de": "Südsudan",
            "fr": "Soudan du sud",
            "nl": "Zuid Soedan",
            "it": "Sudan del Sud",
            "cn": "南苏丹",
            "zh": "南蘇丹",
            "ee": "Lõuna-Sudaan",
            "jp": "南スーダン",
            "he": "דרום סודן",
            "el": "Νότιο Σουδάν"
        },
        "dial_code": "+211",
        "code": "SS",
        "flag": "🇸🇸"
    },
    {
        "name": {
            "en": "Sudan",
            "ru": "Судан",
            "pl": "Sudan",
            "ua": "Судан",
            "cz": "Súdán",
            "by": "Судан",
            "pt": "Sudão",
            "es": "Sudán",
            "ro": "Sudan",
            "bg": "Судан",
            "de": "Sudan",
            "fr": "Soudan",
            "nl": "Soedan",
            "it": "Sudan",
            "cn": "苏丹",
            "zh": "蘇丹",
            "ee": "Sudaan",
            "jp": "スーダン",
            "he": "סודן",
            "el": "Σουδάν"
        },
        "dial_code": "+249",
        "code": "SD",
        "flag": "🇸🇩"
    },
    {
        "name": {
            "en": "Syrian Arab Republic",
            "ru": "Сирийская Арабская Республика",
            "pl": "Republika Syryjsko-Arabska",
            "ua": "Сирійська Арабська Республіка",
            "cz": "Syrská Arabská republika",
            "by": "Сірыйская Арабская Рэспубліка",
            "pt": "Síria",
            "es": "República Árabe Siria",
            "ro": "Republica Araba Siriana",
            "bg": "Сирийска Арабска Република",
            "de": "Syrische Arabische Republik",
            "fr": "République arabe syrienne",
            "nl": "Syrische Arabische Republiek",
            "it": "Repubblica Araba Siriana",
            "cn": "阿拉伯叙利亚共和国",
            "zh": "阿拉伯敘利亞共和國",
            "ee": "Süüria Araabia Vabariik",
            "jp": "シリアアラブ共和国",
            "he": "סוריה",
            "el": "Συρία"
        },
        "dial_code": "+963",
        "code": "SY",
        "flag": "🇸🇾"
    },
    {
        "name": {
            "en": "Uganda",
            "ru": "Уганда",
            "pl": "Uganda",
            "ua": "Уганда",
            "cz": "Uganda",
            "by": "Уганда",
            "pt": "Uganda",
            "es": "Uganda",
            "ro": "Uganda",
            "bg": "Уганда",
            "de": "Uganda",
            "fr": "Ouganda",
            "nl": "Oeganda",
            "it": "Uganda",
            "cn": "乌干达",
            "zh": "烏干達",
            "ee": "Uganda",
            "jp": "ウガンダ",
            "he": "אוגנדה",
            "el": "Ουγκάντα"
        },
        "dial_code": "+256",
        "code": "UG",
        "flag": "🇺🇬"
    },
    {
        "name": {
            "en": "Yemen",
            "ru": "Йемен",
            "pl": "Jemen",
            "ua": "Ємен",
            "cz": "Jemen",
            "by": "Емен",
            "pt": "Iémen",
            "es": "Yemen",
            "ro": "Yemen",
            "bg": "Йемен",
            "de": "Jemen",
            "fr": "Yémen",
            "nl": "Jemen",
            "it": "Yemen",
            "cn": "也门",
            "zh": "也門",
            "ee": "Jeemen",
            "jp": "イエメン",
            "he": "תימן",
            "el": "Υεμένη"
        },
        "dial_code": "+967",
        "code": "YE",
        "flag": "🇾🇪"
    },
    {
        "name": {
            "en": "Zambia",
            "ru": "Замбия",
            "pl": "Zambia",
            "ua": "Замбія",
            "cz": "Zambie",
            "by": "Замбія",
            "pt": "Zâmbia",
            "es": "Zambia",
            "ro": "Zambia",
            "bg": "Замбия",
            "de": "Sambia",
            "fr": "Zambie",
            "nl": "Zambia",
            "it": "Zambia",
            "cn": "赞比亚",
            "zh": "讚比亞",
            "ee": "Sambia",
            "jp": "ザンビア",
            "he": "זמביה",
            "el": "Ζάμπια"
        },
        "dial_code": "+260",
        "code": "ZM",
        "flag": "🇿🇲"
    }
];
